// Validates: REQ-004.
// Per: ADR-0022.
// Discipline: C-14.
package admin_test

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/septagon-oss/pk-modules/pkg/portslib"
)

// TestDashboardRendersTokenDrivenUI verifies the redesigned dashboard: the
// stat tiles, the humanized module card, and — critically — that the served
// stylesheet is token-driven (a pk-design :root block generated by
// tokens.CSSVars precedes the atomic rules).
func TestDashboardRendersTokenDrivenUI(t *testing.T) {
	t.Parallel()
	m := newModule(t)
	resource := testResource()
	resource.ModuleID = "api_key_management"
	resource.EntityName = "APIKey"
	resource.SingularLabel = "API key"
	resource.PluralLabel = "API keys"
	resource.APIPath = "/api/v1/api-keys"
	if err := m.Registrar().RegisterResource(resource); err != nil {
		t.Fatal(err)
	}
	if err := m.Registrar().RegisterPage(portslib.AdminPage{
		ModuleID: "api_key_management", Path: "/admin/api-keys", Title: "API keys",
		Render: func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(200) },
	}); err != nil {
		t.Fatal(err)
	}

	// Dashboard HTML.
	rec := httptest.NewRecorder()
	m.HTTPHandler().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/admin", nil))
	if rec.Code != http.StatusOK {
		t.Fatalf("dashboard status = %d", rec.Code)
	}
	body := rec.Body.String()
	for _, want := range []string{
		`class="pk-stat"`,
		`<dd>1</dd>`,
		`class="pk-module-row"`,
		"API keys",
		"Operational",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("dashboard body missing %q", want)
		}
	}

	// Stylesheet: token-driven (generated :root block) + Content-Type.
	css := httptest.NewRecorder()
	m.HTTPHandler().ServeHTTP(css, httptest.NewRequest(http.MethodGet, "/admin/static/_admin.css", nil))
	if ct := css.Header().Get("Content-Type"); !strings.HasPrefix(ct, "text/css") {
		t.Fatalf("CSS Content-Type = %q, want text/css", ct)
	}
	sheet := css.Body.String()
	for _, want := range []string{
		":root {",
		"--pk-color-text-primary: #15221f",
		"--pk-space-4: 16px",
		"--pk-radius-md: 8px",
		".pk-stat",
		".pk-module-row",
	} {
		if !strings.Contains(sheet, want) {
			t.Errorf("served CSS missing %q (token-driven layer or atomic rules absent)", want)
		}
	}
}

// The console is client-rendered: it reads entity ids out of JSON list
// responses and builds API URLs in the browser. That coupling is invisible to
// Go tooling, and it is exactly how a shipped release once left the console able
// to list entities but unable to open, edit, or delete one — the script still
// addressed the API with encodeURIComponent after the server began requiring the
// canonical opaque segment.
//
// This pins the two halves together: the script must address the API with the
// same encoding pathsegment produces, and must keep using encodeURIComponent for
// links into the console's own pages, which the admin shell parses itself.
func TestAdminScriptAddressesTheAPIWithCanonicalSegments(t *testing.T) {
	t.Parallel()

	m := newModule(t)
	rec := httptest.NewRecorder()
	m.HTTPHandler().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/admin/static/_admin.js", nil))
	if rec.Code != http.StatusOK {
		t.Fatalf("GET /admin/static/_admin.js = %d", rec.Code)
	}
	script := rec.Body.String()

	if strings.Contains(script, "${resource.api_path}/${encodeURIComponent(") {
		t.Error("script addresses the API with encodeURIComponent; the API requires the canonical opaque segment, which rejects percent escapes")
	}
	if !strings.Contains(script, "${resource.api_path}/${apiSegment(") {
		t.Error("script no longer addresses the API through apiSegment")
	}
	if !strings.Contains(script, "encodeURIComponent(id)") {
		t.Error("links into the console's own pages should still use encodeURIComponent; the admin shell parses those paths itself")
	}

	// The encoder must agree with the server byte for byte.
	want, ok := portslib.EncodeEntityID("héllo/world")
	if !ok {
		t.Fatal("EncodeEntityID refused a legitimate id")
	}
	if !strings.HasPrefix(want, "id-") {
		t.Fatalf("unexpected canonical form %q", want)
	}
	for _, fragment := range []string{
		`return ` + "`id-${hex}`",
		"new TextEncoder().encode(String(id))",
		`byte.toString(16).padStart(2, "0")`,
	} {
		if !strings.Contains(script, fragment) {
			t.Errorf("apiSegment must produce %s; missing %q", want[:3]+"<lowercase hex of the id's UTF-8 bytes>", fragment)
		}
	}
}
