// Validates: REQ-004.
// Per: ADR-0022.
// Discipline: C-14.
package admin_test

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/septagon-oss/pk-modules/pkg/portslib"
)

// TestDashboardRendersTokenDrivenUI verifies the redesigned dashboard: the
// stat tiles, the humanized module card, and — critically — that the served
// stylesheet is token-driven (a pk-design :root block generated by
// tokens.CSSVars precedes the atomic rules).
func TestDashboardRendersTokenDrivenUI(t *testing.T) {
	t.Parallel()
	m := newModule(t)
	resource := testResource()
	resource.ModuleID = "api_key_management"
	resource.EntityName = "APIKey"
	resource.SingularLabel = "API key"
	resource.PluralLabel = "API keys"
	resource.APIPath = "/api/v1/api-keys"
	if err := m.Registrar().RegisterResource(resource); err != nil {
		t.Fatal(err)
	}
	if err := m.Registrar().RegisterPage(portslib.AdminPage{
		ModuleID: "api_key_management", Path: "/admin/api-keys", Title: "API keys",
		Render: func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(200) },
	}); err != nil {
		t.Fatal(err)
	}

	// Dashboard HTML.
	rec := httptest.NewRecorder()
	m.HTTPHandler().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/admin", nil))
	if rec.Code != http.StatusOK {
		t.Fatalf("dashboard status = %d", rec.Code)
	}
	body := rec.Body.String()
	for _, want := range []string{
		`class="pk-stat"`,
		`<dd>1</dd>`,
		`class="pk-module-row"`,
		"API keys",
		"Operational",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("dashboard body missing %q", want)
		}
	}

	// Stylesheet: token-driven (generated :root block) + Content-Type.
	css := httptest.NewRecorder()
	m.HTTPHandler().ServeHTTP(css, httptest.NewRequest(http.MethodGet, "/admin/static/_admin.css", nil))
	if ct := css.Header().Get("Content-Type"); !strings.HasPrefix(ct, "text/css") {
		t.Fatalf("CSS Content-Type = %q, want text/css", ct)
	}
	sheet := css.Body.String()
	for _, want := range []string{
		":root {",
		"--pk-color-text-primary: #15221f",
		"--pk-space-4: 16px",
		"--pk-radius-md: 8px",
		".pk-stat",
		".pk-module-row",
	} {
		if !strings.Contains(sheet, want) {
			t.Errorf("served CSS missing %q (token-driven layer or atomic rules absent)", want)
		}
	}
}
