// Validates: REQ-004.
// Per: ADR-0022.
// Discipline: C-14.
package admin_test

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/septagon-oss/pk-modules/pkg/portslib"
)

// TestDashboardRendersTokenDrivenUI verifies the redesigned dashboard: the
// stat tiles, the humanized module card, and — critically — that the served
// stylesheet is token-driven (a pk-design :root block generated by
// tokens.CSSVars precedes the atomic rules).
func TestDashboardRendersTokenDrivenUI(t *testing.T) {
	t.Parallel()
	m := newModule(t)
	if err := m.Registrar().RegisterEntityCRUD("api_key_management", "APIKey", "/api/v1/api-keys"); err != nil {
		t.Fatal(err)
	}
	if err := m.Registrar().RegisterPage(portslib.AdminPage{
		ModuleID: "api_key_management", Path: "/admin/api-keys", Title: "API keys",
		Render: func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(200) },
	}); err != nil {
		t.Fatal(err)
	}

	// Dashboard HTML.
	rec := httptest.NewRecorder()
	m.HTTPHandler().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/admin", nil))
	if rec.Code != http.StatusOK {
		t.Fatalf("dashboard status = %d", rec.Code)
	}
	body := rec.Body.String()
	for _, want := range []string{
		`class="pk-stat"`,        // stat tiles present
		`pk-stat-num">1`,         // one module registered a surface
		`pk-stat-label">Modules`, //
		`class="pk-card-head"`,   // module card
		"API Keys",               // humanized module name (from api_key_management)
		"Operational",            // status pill
	} {
		if !strings.Contains(body, want) {
			t.Errorf("dashboard body missing %q", want)
		}
	}

	// Stylesheet: token-driven (generated :root block) + Content-Type.
	css := httptest.NewRecorder()
	m.HTTPHandler().ServeHTTP(css, httptest.NewRequest(http.MethodGet, "/admin/static/_admin.css", nil))
	if ct := css.Header().Get("Content-Type"); !strings.HasPrefix(ct, "text/css") {
		t.Fatalf("CSS Content-Type = %q, want text/css", ct)
	}
	sheet := css.Body.String()
	for _, want := range []string{
		":root {",
		"--pk-color-text-primary: #111827",
		"--pk-space-4: 16px",
		"--pk-radius-md: 10px",
		".pk-stat",  // atomic rules follow the tokens
		".pk-card ", // organism
	} {
		if !strings.Contains(sheet, want) {
			t.Errorf("served CSS missing %q (token-driven layer or atomic rules absent)", want)
		}
	}
}
